/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const InsuranceType = IDL.Variant({
  'travel' : IDL.Null,
  'life' : IDL.Null,
  'personalAccident' : IDL.Null,
  'property' : IDL.Null,
  'vehicle' : IDL.Null,
  'health' : IDL.Null,
});
export const Time = IDL.Int;
export const CustomerForm = IDL.Record({
  'id' : IDL.Nat,
  'uploadedDocuments' : IDL.Vec(ExternalBlob),
  'name' : IDL.Text,
  'insuranceInterests' : IDL.Vec(InsuranceType),
  'feedback' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const AppSettings = IDL.Record({
  'officeHours' : IDL.Text,
  'maintenanceMode' : IDL.Bool,
  'contactEmail' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'serviceUsed' : IDL.Text,
  'clientName' : IDL.Text,
  'feedback' : IDL.Text,
  'rating' : IDL.Nat,
});
export const ServiceInfo = IDL.Record({
  'title' : IDL.Text,
  'icon' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
});
export const SiteContent = IDL.Record({
  'homeTitle' : IDL.Text,
  'heroText' : IDL.Text,
  'heroImage' : IDL.Opt(ExternalBlob),
  'generalInfo' : IDL.Text,
  'testimonials' : IDL.Vec(Testimonial),
  'homeDescription' : IDL.Text,
  'services' : IDL.Vec(ServiceInfo),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminLoginWithPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllForms' : IDL.Func([], [IDL.Vec(CustomerForm)], ['query']),
  'getAppSettings' : IDL.Func([], [AppSettings], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFormById' : IDL.Func([IDL.Nat], [IDL.Opt(CustomerForm)], ['query']),
  'getFormsByInsuranceType' : IDL.Func(
      [InsuranceType],
      [IDL.Vec(CustomerForm)],
      ['query'],
    ),
  'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'recordVisitor' : IDL.Func([], [], []),
  'resetAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitForm' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(InsuranceType),
        IDL.Text,
        IDL.Vec(ExternalBlob),
      ],
      [],
      [],
    ),
  'updateAppSettings' : IDL.Func([AppSettings], [], []),
  'updateSiteContent' : IDL.Func([SiteContent], [], []),
  'updateUserProfile' : IDL.Func([IDL.Principal, UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const InsuranceType = IDL.Variant({
    'travel' : IDL.Null,
    'life' : IDL.Null,
    'personalAccident' : IDL.Null,
    'property' : IDL.Null,
    'vehicle' : IDL.Null,
    'health' : IDL.Null,
  });
  const Time = IDL.Int;
  const CustomerForm = IDL.Record({
    'id' : IDL.Nat,
    'uploadedDocuments' : IDL.Vec(ExternalBlob),
    'name' : IDL.Text,
    'insuranceInterests' : IDL.Vec(InsuranceType),
    'feedback' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const AppSettings = IDL.Record({
    'officeHours' : IDL.Text,
    'maintenanceMode' : IDL.Bool,
    'contactEmail' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'serviceUsed' : IDL.Text,
    'clientName' : IDL.Text,
    'feedback' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const ServiceInfo = IDL.Record({
    'title' : IDL.Text,
    'icon' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
  });
  const SiteContent = IDL.Record({
    'homeTitle' : IDL.Text,
    'heroText' : IDL.Text,
    'heroImage' : IDL.Opt(ExternalBlob),
    'generalInfo' : IDL.Text,
    'testimonials' : IDL.Vec(Testimonial),
    'homeDescription' : IDL.Text,
    'services' : IDL.Vec(ServiceInfo),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminLoginWithPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllForms' : IDL.Func([], [IDL.Vec(CustomerForm)], ['query']),
    'getAppSettings' : IDL.Func([], [AppSettings], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFormById' : IDL.Func([IDL.Nat], [IDL.Opt(CustomerForm)], ['query']),
    'getFormsByInsuranceType' : IDL.Func(
        [InsuranceType],
        [IDL.Vec(CustomerForm)],
        ['query'],
      ),
    'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'recordVisitor' : IDL.Func([], [], []),
    'resetAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitForm' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(InsuranceType),
          IDL.Text,
          IDL.Vec(ExternalBlob),
        ],
        [],
        [],
      ),
    'updateAppSettings' : IDL.Func([AppSettings], [], []),
    'updateSiteContent' : IDL.Func([SiteContent], [], []),
    'updateUserProfile' : IDL.Func([IDL.Principal, UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };