/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomerForm {
  'id' : bigint,
  'uploadedDocuments' : Array<ExternalBlob>,
  'name' : string,
  'insuranceInterests' : Array<InsuranceType>,
  'feedback' : string,
  'email' : string,
  'address' : string,
  'timestamp' : Time,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export type InsuranceType = { 'travel' : null } |
  { 'life' : null } |
  { 'personalAccident' : null } |
  { 'property' : null } |
  { 'vehicle' : null } |
  { 'health' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VisitorAnalytics {
  'totalVisitors' : bigint,
  'submissions' : bigint,
  'pageViews' : bigint,
  'uniqueVisitors' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllForms' : ActorMethod<[], Array<CustomerForm>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFormById' : ActorMethod<[bigint], [] | [CustomerForm]>,
  'getFormsByInsuranceType' : ActorMethod<[InsuranceType], Array<CustomerForm>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitorCount' : ActorMethod<[], bigint>,
  'getVisitorStats' : ActorMethod<[], VisitorAnalytics>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordVisitor' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitForm' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Array<InsuranceType>,
      string,
      Array<ExternalBlob>,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];